import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "src/store/**/*.ts",
        "src/data/**/*.ts",
        "src/components/catalog/**/*.tsx",
        "src/components/detail/**/*.tsx",
        "src/components/home/CTAFinal.tsx",
        "src/components/home/Hero.tsx",
        "src/components/home/DolorConvencional.tsx",
        "src/components/home/ComoFunciona.tsx",
        "src/components/motion/**/*.tsx",
        "src/components/mi-pedido/**/*.tsx",
        "src/components/agenda/CitaCancelarView.tsx",
        "src/components/admin/LinkSeguimiento.tsx",
        "src/lib/rate-limit-db.ts",
        "src/lib/email/escape-html.ts",
        "src/lib/email/pedido-estado-email.ts",
        "src/app/api/leads/route.ts",
        "src/app/api/mi-pedido/route.ts",
        "src/app/api/pedido/route.ts",
        "src/app/api/agenda/citas/[[]id]/cancelar/route.ts",
        "src/lib/recibos/**/*.ts",
        "src/lib/validators/recibo.ts",
        "src/lib/email/recibo-emails.ts",
        "src/lib/admin/storage.ts",
        "src/components/admin/recibos/**/*.tsx",
        "src/components/recibo/**/*.tsx",
        "src/app/recibo/**/*.tsx",
        "src/app/api/recibos/**/*.ts",
        "src/lib/legal/**/*.ts",
        "src/lib/log-seguro.ts",
        "src/data/legal/**/*.ts",
        "src/components/legal/**/*.tsx",
        "src/app/privacidad/**/*.tsx",
        "src/app/terminos/**/*.tsx",
        "src/app/api/webhooks/**/*.ts",
        "src/lib/whatsapp.ts",
        "src/lib/validators/configurador.ts",
        "src/app/admin/**/*.{ts,tsx}",
        "src/app/api/admin/**/*.ts",
        "src/lib/agenda/**/*.ts",
        "src/lib/envios/**/*.ts",
      ],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/test/**",
      ],
      thresholds: {
        statements: 95,
        branches: 95,
        functions: 95,
        lines: 95,
      },
    },
  },
});
